import { useId } from "react";
import { OutcomeBadge } from "./OutcomeBadge.tsx";
import { bundle } from "../examples.ts";

interface Props {
  activeId: string | null;
  onSelect: (id: string) => void;
  onCopyToForm: (id: string) => void;
}

export function ExampleList({ activeId, onSelect, onCopyToForm }: Props) {
  const id = useId();
  return (
    <section className="panel" aria-labelledby={`${id}-h`}>
      <h2 id={`${id}-h`}>Synthetic examples</h2>
      <p className="muted">
        Each example pairs a <strong>synthetic</strong> SEP-24 record (no real anchor produced it) with a <strong>recorded Stellar testnet transaction</strong>. They were generated by the SDK and are recomputed here in your browser.
      </p>
      <ul className="examples">
        {bundle.cases.map((c) => (
          <li key={c.id}>
            <button type="button" className="example" aria-pressed={activeId === c.id} onClick={() => onSelect(c.id)} data-example-id={c.id}>
              <span className="example-title">{c.case.title}</span>
              <OutcomeBadge outcome={c.report.overall ?? "insufficient_evidence"} />
            </button>
          </li>
        ))}
      </ul>
      {activeId ? (
        <button type="button" className="link-button" onClick={() => onCopyToForm(activeId)}>
          Copy the selected example into the form below to edit it
        </button>
      ) : null}
    </section>
  );
}
