// Verifies that the studio is built against exactly the SDK artifact recorded in pairing.json.
// Run by `pnpm run build` and CI. Fails loudly instead of letting a drifted SDK or schema ship.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const sha = (p) => createHash("sha256").update(readFileSync(p)).digest("hex");
const pairing = JSON.parse(readFileSync("pairing.json", "utf8"));
const errors = [];

if (sha(pairing.sdk.tarball) !== pairing.sdk.tarballSha256) errors.push(`${pairing.sdk.tarball} does not match tarballSha256 in pairing.json`);

const installed = JSON.parse(readFileSync("node_modules/@anas.abubakar/anchortrace-sdk/package.json", "utf8"));
if (installed.version !== pairing.sdk.version) errors.push(`installed SDK is ${installed.version}, pairing.json says ${pairing.sdk.version}`);

for (const [vendored, expected] of Object.entries(pairing.vendoredSchemas)) {
  const name = vendored.split("/").pop();
  if (sha(vendored) !== expected) errors.push(`${vendored} differs from the hash in pairing.json`);
  const shipped = `node_modules/@anas.abubakar/anchortrace-sdk/schema/${name}`;
  if (sha(shipped) !== expected) errors.push(`${shipped} (installed SDK) differs from the vendored ${vendored}`);
}

const examples = JSON.parse(readFileSync("node_modules/@anas.abubakar/anchortrace-sdk/examples/examples.v1.json", "utf8"));
if (examples.reportVersion !== pairing.schemaVersions.report) errors.push(`SDK examples are report schema ${examples.reportVersion}, studio expects ${pairing.schemaVersions.report}`);
if (examples.toolVersion !== pairing.sdk.version) errors.push(`SDK examples were generated by ${examples.toolVersion}, studio pins ${pairing.sdk.version}`);

if (errors.length > 0) {
  console.error("SDK pairing check failed:\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}
console.log(`pairing OK: sdk ${pairing.sdk.version} (${pairing.sdk.gitTag}), tarball sha256 ${pairing.sdk.tarballSha256.slice(0, 12)}..., report schema ${pairing.schemaVersions.report}`);
