import { CASE_VERSION, EVIDENCE_VERSION, REPORT_VERSION, TOOL_VERSION, parseReport, type Report } from "@anas.abubakar/anchortrace-sdk";
import { pairing } from "./pairing.ts";

export interface Compatibility {
  ok: boolean;
  problems: string[];
}

/**
 * Compares the SDK code actually bundled into this page with the versions the studio was released against.
 * A mismatch means the studio would be interpreting reports or evidence with a different contract than it was built for.
 */
export function checkCompatibility(bundle: { reportVersion: string; toolVersion: string }): Compatibility {
  const problems: string[] = [];
  if (TOOL_VERSION !== pairing.sdk.version) problems.push(`bundled SDK is ${TOOL_VERSION}, studio is paired with ${pairing.sdk.version}`);
  if (REPORT_VERSION !== pairing.schemaVersions.report) problems.push(`SDK report schema is v${REPORT_VERSION}, studio expects v${pairing.schemaVersions.report}`);
  if (EVIDENCE_VERSION !== pairing.schemaVersions.evidence) problems.push(`SDK evidence schema is v${EVIDENCE_VERSION}, studio expects v${pairing.schemaVersions.evidence}`);
  if (CASE_VERSION !== pairing.schemaVersions.case) problems.push(`SDK case schema is v${CASE_VERSION}, studio expects v${pairing.schemaVersions.case}`);
  if (bundle.reportVersion !== REPORT_VERSION) problems.push(`bundled examples are report schema v${bundle.reportVersion}, SDK reports v${REPORT_VERSION}`);
  if (bundle.toolVersion !== TOOL_VERSION) problems.push(`bundled examples were generated by SDK ${bundle.toolVersion}, bundled SDK is ${TOOL_VERSION}`);
  return { ok: problems.length === 0, problems };
}

/** Validate a previously saved report before showing it; gives a version-specific message instead of a generic schema error. */
export function openSavedReport(value: unknown): { ok: true; report: Report } | { ok: false; message: string; issues: string[] } {
  if (value === null || typeof value !== "object" || !("reportVersion" in value)) {
    return { ok: false, message: "This is not an AnchorTrace report (no reportVersion field).", issues: [] };
  }
  const v = (value as { reportVersion: unknown }).reportVersion;
  if (v !== REPORT_VERSION) {
    return { ok: false, message: `This report uses schema v${String(v)}; this studio reads v${REPORT_VERSION} only (SDK ${TOOL_VERSION}). Use a studio paired with the SDK that produced it.`, issues: [] };
  }
  const p = parseReport(value);
  return p.ok ? { ok: true, report: p.report } : { ok: false, message: "The report does not match the v1 report schema.", issues: p.error.split("; ") };
}
