import bundleJson from "@anasabubakar/anchortrace-sdk/examples/examples.v1.json";
import type { Case, Report } from "@anasabubakar/anchortrace-sdk";

export interface ExampleEntry {
  id: string;
  case: Case;
  report: Report;
}

export interface ExamplesBundle {
  examplesVersion: string;
  toolVersion: string;
  reportVersion: string;
  generatedWith: string;
  generatedAt: string;
  cases: ExampleEntry[];
}

/** Cases and reports generated by the SDK (scripts/gen-examples.ts in anchortrace-sdk). The studio never edits them. */
export const bundle = bundleJson as unknown as ExamplesBundle;
